# PyTorch Fundamentals

#### Check pytorch installation version
Installed torch version is 2.14.1+cpu

In [1]:
import torch
print(torch.__version__)

2.11.0+cu130


#### Introduction to tensors

* Tensors are the fundamental building block of machine learning to represent data in a numerical way.

* For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

![Tensor](https://github.com/thamizhannal/pytorch-deep-learning/blob/main/notebooks/imgs/tensor.png?raw=1)


#### creating tensors

#### Scaler Tensor
A scalar is a single number with zero dimension tensor.




In [2]:
scalar_x = torch.tensor(7)
print(scalar_x)

# To get the dimension
print(f"Dimension:{scalar_x.ndim}")

# To retrive the number from the tensor
print(scalar_x.item())

tensor(7)
Dimension:0
7


#### vector tensor
A vector is a an array with one or more dimension
* single dimension array E.g. 1-d array, 2-d array, 3-d array or n-d array
* E.g. Consider House is a class, then  you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

In [3]:
# Vector
vector = torch.tensor([7, 7])
print(f"vector val:{vector}")

# Check the number of dimensions of vector
print(f"Dimension:{vector.ndim}")

# The number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([)
# and you only need to count one side
print(f"vector shape:{vector.shape}")

vector val:tensor([7, 7])
Dimension:1
vector shape:torch.Size([2])


#### Matrix


MATRIX has two dimensions (did you count the number of square brackets on the outside of one side?).

In [4]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)

# Check number of dimensions
print(MATRIX.ndim)


# shape of the matrix
print(MATRIX.shape)




tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


#### Tensor

![Tensor Visual](https://github.com/thamizhannal/pytorch-deep-learning/blob/main/notebooks/imgs/tensor_visual_image.png?raw=1)


In [5]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)

# Check number of dimensions for TENSOR
print(TENSOR.ndim)

# Check shape of TENSOR
print(TENSOR.shape)


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


![Tensor Visual](https://github.com/thamizhannal/pytorch-deep-learning/blob/main/notebooks/imgs/tensor_visual_image.png?raw=1)

Note: You might've noticed me using lowercase letters for scalar and vector and uppercase letters for MATRIX and TENSOR. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a. And matrices and tensors denoted as uppercase letters such as X or W.

![Compare various Tensor Types](https://github.com/thamizhannal/pytorch-deep-learning/blob/main/notebooks/imgs/tensor_types.png?raw=1)

![Sample Tensor types](https://github.com/thamizhannal/pytorch-deep-learning/blob/main/notebooks/imgs/tensors.png?raw=1)



#### Random tensors
In ML models such as neural networks manipulate and seek patterns within tensors.

A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

```bash
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...
```

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

```python
 torch.rand() and passing in the size parameter.
 ```


In [6]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3498, 0.8863, 0.8967, 0.0204],
         [0.2380, 0.2450, 0.3591, 0.5872],
         [0.2474, 0.2729, 0.7001, 0.1566]]),
 torch.float32)

In [7]:
# Create a random tensor of size (3, 3, 4)
random_tensor = torch.rand(size=(3, 3, 4))
random_tensor, random_tensor.dtype

(tensor([[[0.1418, 0.9258, 0.9932, 0.6163],
          [0.3408, 0.2853, 0.5755, 0.9485],
          [0.4165, 0.5184, 0.5446, 0.3558]],
 
         [[0.5348, 0.6752, 0.9079, 0.9144],
          [0.6897, 0.2889, 0.8985, 0.8793],
          [0.1741, 0.5589, 0.7120, 0.3042]],
 
         [[0.1869, 0.1291, 0.7627, 0.6748],
          [0.6784, 0.8092, 0.4208, 0.9077],
          [0.7078, 0.0140, 0.1515, 0.4603]]]),
 torch.float32)

#### Zeros and ones
To create a tensor want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

```python
create a tensor full of zeros with torch.zeros()
```


In [8]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [9]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

#### Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

* start = start of range (e.g. 0)
* end = end of range (e.g. 10)
* step = how many steps in between each value (e.g. 1)

##### Note: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.

In [10]:
zero_to_ten_rnd = torch.arange(start=0, end=10, step=1)
zero_to_ten_rnd

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importent Note:
* In DNN, somce cases one has to create a tensor of particular dimension with all zeros or ones'

* Sometimes you might want one tensor of a certain type with the same shape as another tensor.

* For example, a tensor of all zeros with the same shape as a previous tensor.

* To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.


In [11]:
tensor_ones = torch.ones_like(zero_to_ten_rnd)
print(tensor_ones)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [12]:
tensor_zeros = torch.zeros_like(zero_to_ten_rnd)
print(tensor_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


#### Tensor datatypes

There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

* The most common type (and generally the default) is torch.float32 or torch.float. This is referred to as "32-bit floating point".

* But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

***So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).***


Resources:

See the PyTorch documentation for a list of all available tensor datatypes.
Read the Wikipedia page for an overview of what precision in computing) is.
Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.

In [13]:
float_32_tensor = torch.tensor(
    [1.0, 5.0, 10.0],
    dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
    device=None, # defaults to None, which uses the default tensor type
    requires_grad=False # if True, operations performed on the tensor are recorded
)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

We'll see more of this device talk later on.

For now let's create a tensor with dtype=torch.float16.

In [14]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

#### Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

* shape - what shape is the tensor? (some operations require specific shape rules)
* dtype - what datatype are the elements within the tensor stored in?
* device - what device is the tensor stored on? (usually GPU or CPU)
Let's create a random tensor and find out details about it.

In [15]:
# create a tensor
tensor_t1 = torch.rand(3,4)
print(tensor_t1)
# print device
print(f"device:{tensor_t1.device}")

#print dim
print(f"Shape:{tensor_t1.shape}")

print(f"dtype:{tensor_t1.dtype}")

tensor([[0.6656, 0.0111, 0.8855, 0.2114],
        [0.9471, 0.6659, 0.7057, 0.7192],
        [0.2785, 0.4317, 0.7654, 0.3897]])
device:cpu
Shape:torch.Size([3, 4])
dtype:torch.float32


#### Manipulating tensors (tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication



##### Basic operations
Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

In [16]:
tensor = torch.tensor([1,2,3])
print(f"tensor:{tensor}")
print(f"Multiply tensor with 1o:{tensor * 10}")
print(f"Add tensor with 5:{tensor + 5}")
print (f"Substract tensor with 3:{tensor - 3}")
print(f"Divide tensor by 2:{tensor/2}")


tensor:tensor([1, 2, 3])
Multiply tensor with 1o:tensor([10, 20, 30])
Add tensor with 5:tensor([6, 7, 8])
Substract tensor with 3:tensor([-2, -1,  0])
Divide tensor by 2:tensor([0.5000, 1.0000, 1.5000])



PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [17]:
torch.multiply(tensor, 5)

tensor([ 5, 10, 15])

However, it's more common to use the operator symbols like * instead of torch.mul()



In [18]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print( tensor * tensor)
print("Equals:", tensor * tensor)


tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


#### Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.



In [19]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])


The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:

![Matrix multiplication](https://github.com/thamizhannal/pytorch-deep-learning/blob/main/notebooks/imgs/matmul.png?raw=1)

Operation	                    Calculation	                    Code <br>
Element-wise multiplication	    [1*1, 2*2, 3*3] = [1, 4, 9]     tensor * tensor <br>
Matrix multiplication	        [1*1 + 2*2 + 3*3] = [14]	    tensor.matmul(tensor)<br>



In [20]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [21]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

#### IMPORTTENT NOTE
* matrix multiplication  using for loop, not recommended
* The in-built torch.matmul() method is faster.


In [22]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.28 ms, sys: 0 ns, total: 1.28 ms
Wall time: 4.2 ms


tensor(14)

In [23]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 297 µs, sys: 0 ns, total: 297 µs
Wall time: 233 µs


tensor(14)

#### One of the most common errors in deep learning (shape errors)
* Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and  sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.


In [24]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

* torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
* tensor.T - where tensor is the desired tensor to transpose.

In [25]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [26]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [27]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [28]:
# You can also use torch.mm() which is a short for torch.matmul().

# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Neural networks are full of matrix multiplications and dot products.

The torch.nn.Linear() module also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

$$ y = x\cdot{A^T} + b $$

Where:

* x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
* A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).

* Note: You might also often see W or another letter like X used to showcase the weights matrix.
* b is the bias term used to slightly offset the weights and inputs.
* y is the output (a manipulation of the input in the hopes to discover patterns in it).
* This is a linear function (you may have seen something like $y = mx+b$ in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.
Try changing the values of in_features and out_features below and see what happens.

In [29]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

#This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6)  # out_features = describes outer value
X = tensor_A

output = linear(X)
print(f"Input X:\n{X}")
print(f"Input shape:{X.shape}\n")
print(f"Output:\n{output} \n Output Shape:{output.shape}")

Input X:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Input shape:torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>) 
 Output Shape:torch.Size([3, 6])


![image.png](imgs/image.png)

####  Finding the min, max, mean, sum, etc (aggregation)
* Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

* First we'll create a tensor and then find the max, min, mean and sum of it.

In [30]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


Note: You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.


In [32]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


(tensor(90), tensor(0), tensor(45.), tensor(450))

#### Positional min/max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).


In [33]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


#### Change tensor datatype
As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

First we'll create a tensor and check its datatype (the default is torch.float32).

In [34]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)
print(tensor)

torch.float32
tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])



Now we'll create another tensor the same as before but change its datatype to torch.float16.

In [35]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [36]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

Note: Different datatypes can be confusing to begin with. But think of it like this, the lower the number (e.g. 32, 16, 8), the less precise a computer stores the value. And with a lower amount of storage, this generally results in faster computation and a smaller overall model. Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts. For more on this, I'd read up about precision in computing).

Exercise: So far we've covered a fair few tensor methods but there's a bunch more in the torch.Tensor documentation, I'd recommend spending 10-minutes scrolling through and looking into any that catch your eye. Click on them and then write them out in code yourself to see what happens.

In [37]:
t1 = torch.tensor([1,2,3,4,5])
print(t1)
print(t1.dtype)

t2 = t1.type(torch.float16)
print(t2)
print(t2.dtype)

t3 = t1.type(torch.float32)
print(t3)
print(t3.dtype)

tensor([1, 2, 3, 4, 5])
torch.int64
tensor([1., 2., 3., 4., 5.], dtype=torch.float16)
torch.float16
tensor([1., 2., 3., 4., 5.])
torch.float32


#### Reshaping, stacking, squeezing and unsqueezing
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

![Reshape,Stack,Squeeze,Unsqueeze](https://github.com/thamizhannal/pytorch-deep-learning/blob/main/notebooks/imgs/tensor_ops.png?raw=1)

* Deep learning models (neural networks) are all about manipulating tensors in some way.
* During the rule of the matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.


In [38]:
# create a tensor
t1 = torch.arange(1.,10.,)
t1, t1.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

#### reshape

In [39]:
# add an extra dimension with torch.reshape().
reshaped_tensor = t1.reshape(1,9)
reshaped_tensor, reshaped_tensor.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [40]:
# change the view with torch.view().
z = t1.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [41]:
# Any change in z changes t1
z[:,0] = 5
z, t1

# At index=0, the value 1 was changed to 5, the same value was updated into t1 as well.



(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

#### Stack

If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().

##### Note: dim=0 represents row based stacking

In [42]:
t1_stacked = torch.stack([t1, t1, t1, t1, t1], dim=0)
z, t1, t1_stacked

# Note: dim=0 represents row based stacking

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

##### Note: dim=1 represents column based stacking


In [43]:
t2_stacked = torch.stack([t1,t1,t1], dim=1)
t1, t2_stacked
# Note: dim=1 represents column based stacking


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 5., 5.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]))

#### squeeze
torch.squeeze() - removing all single dimensions from a tensor

In [44]:
# Original tesnor
print(f"t1 reshaped tensor:{reshaped_tensor} ")
print(f"previous shapre: {reshaped_tensor.shape}")

# remove extra dim from reshaped_tensor
squeezed_tensor = reshaped_tensor.squeeze()

print(f"New tensor:{squeezed_tensor} ")
print(f"New shape: {squeezed_tensor.shape}")


t1 reshaped tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
previous shapre: torch.Size([1, 9])
New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
New shape: torch.Size([9])


#### unsqueeze
And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.



In [45]:
# Original tesnor
print(f"t1 reshaped tensor:{squeezed_tensor} ")
print(f"previous shapre: {squeezed_tensor.shape}")

# remove extra dim from reshaped_tensor
unsqueezed_tensor = squeezed_tensor.unsqueeze(dim=0)

print(f"Unsqueeze tensor:{unsqueezed_tensor} ")
print(f"Unsqueeze tensor shape: {unsqueezed_tensor.shape}")

t1 reshaped tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
previous shapre: torch.Size([9])
Unsqueeze tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
Unsqueeze tensor shape: torch.Size([1, 9])


In [46]:
# Original tesnor
print(f"t1 reshaped tensor:{squeezed_tensor} ")
print(f"previous shapre: {squeezed_tensor.shape}")

# remove extra dim from reshaped_tensor
unsqueezed_tensor = squeezed_tensor.unsqueeze(dim=1)

print(f"Unsqueeze tensor:{unsqueezed_tensor} ")
print(f"Unsqueeze tensor shape: {unsqueezed_tensor.shape}")

t1 reshaped tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
previous shapre: torch.Size([9])
Unsqueeze tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) 
Unsqueeze tensor shape: torch.Size([9, 1])


#### Permute

You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [47]:
# create a tensor with specific shape
x_origional = torch.rand(size=(224,224,3))

#Permute the origional tensor to rearrange the axis order
x_permuted = x_origional.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape:{x_origional.shape}")
print(f"New shape:{x_permuted.shape}")



Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [48]:
x_origional = torch.rand(size=(3,2,4))

#Permute the origional tensor to rearrange the axis order
x_permuted = x_origional.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print({x_origional})
print(f"Previous shape:{x_origional.shape}")
print({x_permuted})
print(f"New shape:{x_permuted.shape}")
# 3 x 2 x 4
# 4 x 3 x 2
#

{tensor([[[0.8016, 0.3649, 0.6286, 0.9663],
         [0.7687, 0.4566, 0.5745, 0.9200]],

        [[0.3230, 0.8613, 0.0919, 0.3102],
         [0.9536, 0.6002, 0.0351, 0.6826]],

        [[0.3743, 0.5220, 0.1336, 0.9666],
         [0.9754, 0.8474, 0.8988, 0.1105]]])}
Previous shape:torch.Size([3, 2, 4])
{tensor([[[0.8016, 0.7687],
         [0.3230, 0.9536],
         [0.3743, 0.9754]],

        [[0.3649, 0.4566],
         [0.8613, 0.6002],
         [0.5220, 0.8474]],

        [[0.6286, 0.5745],
         [0.0919, 0.0351],
         [0.1336, 0.8988]],

        [[0.9663, 0.9200],
         [0.3102, 0.6826],
         [0.9666, 0.1105]]])}
New shape:torch.Size([4, 3, 2])


![Tensor Permute](https://github.com/thamizhannal/pytorch-deep-learning/blob/main/notebooks/imgs/permute.png?raw=1)

Note: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.


#### Indexing (selecting data from tensors)
* Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).
To do so, you can use indexing.

* If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.


In [49]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing values goes outer dimension -> inner dimension (check out the square brackets).



In [50]:
# Index bracket by bracket
print(f"First square bracket:\n {x[0]}")

First square bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [51]:
print(f"Seconnd square bracket: {x[0][0]}")
print(f"Seconnd square bracket: {x[0][2]}")

Seconnd square bracket: tensor([1, 2, 3])
Seconnd square bracket: tensor([7, 8, 9])


In [52]:
print(f"Third square bracket:{x[0][0][0]}")
print(f"Third square bracket:{x[0][1][2]}")

Third square bracket:1
Third square bracket:6



You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [53]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:,0]

tensor([[1, 2, 3]])

In [54]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [55]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [56]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])


Indexing can be quite confusing to begin with, especially with larger tensors (I still have to try indexing multiple times to get it right). But with a bit of practice and following the data explorer's motto (visualize, visualize, visualize), you'll start to get the hang of it.

#### PyTorch tensors & NumPy¶

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

NOTE: Converting numpy array into pytorch, then back to numpy

In [57]:
import torch
import numpy as np
np.__version__
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array)
print(tensor) # printing numpy array & tensor



[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


* Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

* However, many PyTorch calculations default to using float32.

* So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

* Because we reassigned tensor above, if you change the tensor, the array stays the same.



In [58]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

And if you want to go from PyTorch tensor to NumPy array, you can call tensor.numpy().



In [59]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

And the same rule applies as above, if you change the original tensor, the new numpy_tensor stays the same.



In [60]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#### Reproducibility (trying to take the random out of random)

In DNN, randomness used to assign weights, later they were learnt from Backpropagation.


How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

***start with random numbers -> tensor operations -> try to make better (again and again and again)***

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where reproducibility comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [61]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.4563, 0.9719, 0.3968, 0.1496],
        [0.4743, 0.9973, 0.4436, 0.9726],
        [0.5194, 0.5337, 0.7050, 0.3362]])

Tensor B:
tensor([[0.7891, 0.1694, 0.1800, 0.7177],
        [0.6988, 0.5510, 0.2485, 0.8518],
        [0.0963, 0.1338, 0.2741, 0.6142]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Just as you might've expected, the tensors come out with different values.

But what if you wanted to create two random tensors with the same values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

Let's try it out by creating some more flavoured random tensors.

In [62]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Nice!

It looks like setting the seed worked.

Resource: What we've just covered only scratches the surface of reproducibility in PyTorch. For more, on reproducibility in general and random seeds, I'd checkout:

The PyTorch reproducibility documentation (a good exercise would be to read through this for 10-minutes and even if you don't understand it now, being aware of it is important).
The Wikipedia random seed page (this'll give a good overview of random seeds and pseudorandomness in general).

#### Running tensors on GPUs (and making faster computations)

* Deep learning algorithms require a lot of numerical operations.

* And by default these operations are often done on a CPU (computer processing unit).

* However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

* If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

* There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

***Note: When I reference "GPU" throughout this course, I'm referencing a Nvidia GPU with CUDA enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.***


#### 1. Getting a GPU

* ***Google Colab***	Easy	Free to use, almost zero setup required, can share work with others as easy as a link	Doesn't save your data outputs, limited compute, subject to timeouts	Follow the Google Colab Guide

* ***Use your own(NVIDEA GPU)***	Medium	Run everything locally on your own machine	GPUs aren't free, require upfront cost	Follow the PyTorch installation guidelines
* ***Cloud computing (AWS, GCP, Azure)***	Medium-Hard	Small upfront cost, access to almost infinite compute	Can get expensive if running continually, takes some time to setup right	Follow the PyTorch installation guidelines


In [64]:
# To check if you've got access to a Nvidia GPU, you can run !nvidia-smi where the ! (also called bang) means "run this on the command line".

!nvidea-smi


/bin/bash: line 1: nvidea-smi: command not found


#### 2. Getting PyTorch to run on the GPU
Once you've got a GPU ready to access, the next step is getting PyTorch to use for storing data (tensors) and computing on data (performing operations on tensors).

To do so, you can use the torch.cuda package.

Rather than talk about it, let's try it out.

You can test if PyTorch has access to a GPU using torch.cuda.is_available().

In [65]:
# chech for GPU
import torch
torch.cuda.is_available()
# If the above outputs True, PyTorch can see and use the GPU, if it outputs False, it can't see the GPU and in that case, you'll have to go back through the installation steps.

True

In [66]:
# Let's create a device variable to store what kind of device is available.

device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

If the above output "cuda" it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output "cpu", our PyTorch code will stick with the CPU.

****Note: In PyTorch, it's best practice to write device agnostic code. This means code that'll run on CPU (always available) or GPU (if available).***

***If you want to do faster computing you can use a GPU but if you want to do much faster computing, you can use multiple GPUs.***


In [67]:
# You can count the number of GPUs PyTorch has access to using torch.cuda.device_count().
torch.cuda.is_available(), torch.cuda.device_count()

# Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across all GPUs).

(True, 1)


### 3. Putting tensors (and models) on the GPU
You can put tensors (and models, we'll see this later) on a specific device by calling to(device) on them. Where device is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our device agnostic code (see above), it'll run on the CPU.

Note: Putting a tensor on GPU using to(device) (e.g. some_tensor.to(device)) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:

some_tensor = some_tensor.to(device)

Let's try creating a tensor and putting it on the GPU (if it's available).

In [68]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

If you have a GPU available, the above code will output something like:

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')

Notice the second tensor has device='cuda:0', this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be 'cuda:0' and 'cuda:1' respectively, up to 'cuda:n').

#### 4. Moving tensors back to the CPU

What if we wanted to move the tensor back to CPU?

For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).

Let's try using the torch.Tensor.numpy() method on our tensor_on_gpu

In [69]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()



TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [73]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
# TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

# The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.
tensor_on_gpu = torch.tensor([1, 2, 3], device='cuda')


# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])