# PyTorch Fundamentals 

#### Check pytorch installation version
Installed torch version is 2.14.1+cpu

In [4]:
import torch
print(torch.__version__)

2.14.1+cpu


#### Introduction to tensors

* Tensors are the fundamental building block of machine learning to represent data in a numerical way.

* For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

![Tensor](imgs/tensor.png)


#### creating tensors

#### Scaler Tensor
A scalar is a single number with zero dimension tensor.




In [5]:
scalar_x = torch.tensor(7)
print(scalar_x)

# To get the dimension
print(f"Dimension:{scalar_x.ndim}")

# To retrive the number from the tensor
print(scalar_x.item())

tensor(7)
Dimension:0
7


#### vector tensor
A vector is a an array with one or more dimension 
* single dimension array E.g. 1-d array, 2-d array, 3-d array or n-d array
* E.g. Consider House is a class, then  you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

In [6]:
# Vector
vector = torch.tensor([7, 7])
print(f"vector val:{vector}")

# Check the number of dimensions of vector
print(f"Dimension:{vector.ndim}")

# The number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) 
# and you only need to count one side
print(f"vector shape:{vector.shape}")

vector val:tensor([7, 7])
Dimension:1
vector shape:torch.Size([2])


#### Matrix


MATRIX has two dimensions (did you count the number of square brackets on the outside of one side?).

In [7]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
print(MATRIX)

# Check number of dimensions
print(MATRIX.ndim)


# shape of the matrix
print(MATRIX.shape)




tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


#### Tensor

![Tensor Visual](imgs/tensor_visual_image.png)


In [8]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)

# Check number of dimensions for TENSOR
print(TENSOR.ndim)

# Check shape of TENSOR
print(TENSOR.shape)


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


![Tensor Visual](imgs/tensor_visual_image.png)

Note: You might've noticed me using lowercase letters for scalar and vector and uppercase letters for MATRIX and TENSOR. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as y or a. And matrices and tensors denoted as uppercase letters such as X or W.

![Compare various Tensor Types](imgs/tensor_types.png)

![Sample Tensor types](imgs/tensors.png)



#### Random tensors
In ML models such as neural networks manipulate and seek patterns within tensors.

A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

```bash
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...
```

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

```python
 torch.rand() and passing in the size parameter.
 ```
 

In [9]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4069, 0.4505, 0.0422, 0.4688],
         [0.5557, 0.7435, 0.9078, 0.3310],
         [0.3765, 0.7958, 0.7559, 0.5425]]),
 torch.float32)

In [10]:
# Create a random tensor of size (3, 3, 4)
random_tensor = torch.rand(size=(3, 3, 4))
random_tensor, random_tensor.dtype

(tensor([[[0.2997, 0.2632, 0.8545, 0.3967],
          [0.8073, 0.1747, 0.0983, 0.2142],
          [0.3705, 0.3917, 0.0339, 0.8452]],
 
         [[0.7988, 0.3708, 0.4697, 0.8537],
          [0.1277, 0.5259, 0.2084, 0.4003],
          [0.1504, 0.1426, 0.3911, 0.0216]],
 
         [[0.3765, 0.1351, 0.7017, 0.5987],
          [0.8387, 0.0348, 0.9034, 0.4158],
          [0.3211, 0.6739, 0.3813, 0.7383]]]),
 torch.float32)

#### Zeros and ones
To create a tensor want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

```python
create a tensor full of zeros with torch.zeros()
```


In [11]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [12]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

#### Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

* start = start of range (e.g. 0)
* end = end of range (e.g. 10)
* step = how many steps in between each value (e.g. 1)

##### Note: In Python, you can use range() to create a range. However in PyTorch, torch.range() is deprecated and may show an error in the future.

In [13]:
zero_to_ten_rnd = torch.arange(start=0, end=10, step=1)
zero_to_ten_rnd

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importent Note:
* In DNN, somce cases one has to create a tensor of particular dimension with all zeros or ones'

* Sometimes you might want one tensor of a certain type with the same shape as another tensor.

* For example, a tensor of all zeros with the same shape as a previous tensor.

* To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.


In [14]:
tensor_ones = torch.ones_like(zero_to_ten_rnd)
print(tensor_ones)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [15]:
tensor_zeros = torch.zeros_like(zero_to_ten_rnd)
print(tensor_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


#### Tensor datatypes

There are many different tensor datatypes available in PyTorch.

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

* The most common type (and generally the default) is torch.float32 or torch.float. This is referred to as "32-bit floating point".

* But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

Note: An integer is a flat round number like 7 whereas a float has a decimal 7.0.

The reason for all of these is to do with precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

***So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).***


Resources:

See the PyTorch documentation for a list of all available tensor datatypes.
Read the Wikipedia page for an overview of what precision in computing) is.
Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.

In [16]:
float_32_tensor = torch.tensor(
    [1.0, 5.0, 10.0],
    dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
    device=None, # defaults to None, which uses the default tensor type
    requires_grad=False # if True, operations performed on the tensor are recorded
)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

We'll see more of this device talk later on.

For now let's create a tensor with dtype=torch.float16.

In [17]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

#### Getting information from tensors
Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

* shape - what shape is the tensor? (some operations require specific shape rules)
* dtype - what datatype are the elements within the tensor stored in?
* device - what device is the tensor stored on? (usually GPU or CPU)
Let's create a random tensor and find out details about it.

In [18]:
# create a tensor
tensor_t1 = torch.rand(3,4)
print(tensor_t1)
# print device
print(f"device:{tensor_t1.device}")

#print dim
print(f"Shape:{tensor_t1.shape}")

print(f"dtype:{tensor_t1.dtype}")

tensor([[0.0014, 0.6348, 0.2992, 0.5601],
        [0.7119, 0.4564, 0.8476, 0.1230],
        [0.0699, 0.5361, 0.2622, 0.1010]])
device:cpu
Shape:torch.Size([3, 4])
dtype:torch.float32


#### Manipulating tensors (tensor operations)
In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication



##### Basic operations
Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

In [20]:
tensor = torch.tensor([1,2,3])
print(f"tensor:{tensor}")
print(f"Multiply tensor with 1o:{tensor * 10}")
print(f"Add tensor with 5:{tensor + 5}")
print (f"Substract tensor with 3:{tensor - 3}")
print(f"Divide tensor by 2:{tensor/2}")


tensor:tensor([1, 2, 3])
Multiply tensor with 1o:tensor([10, 20, 30])
Add tensor with 5:tensor([6, 7, 8])
Substract tensor with 3:tensor([-2, -1,  0])
Divide tensor by 2:tensor([0.5000, 1.0000, 1.5000])



PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [21]:
torch.multiply(tensor, 5)

tensor([ 5, 10, 15])

However, it's more common to use the operator symbols like * instead of torch.mul()



In [23]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print( tensor * tensor)
print("Equals:", tensor * tensor)


tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


#### Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.



In [24]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])


The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:

![Matrix multiplication](imgs/matmul.png)

Operation	                    Calculation	                    Code <br>
Element-wise multiplication	    [1*1, 2*2, 3*3] = [1, 4, 9]     tensor * tensor <br>
Matrix multiplication	        [1*1 + 2*2 + 3*3] = [14]	    tensor.matmul(tensor)<br>



In [25]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [26]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

#### IMPORTTENT NOTE
* matrix multiplication  using for loop, not recommended
* The in-built torch.matmul() method is faster.


In [27]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 20.8 ms


tensor(14)

In [28]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 72.5 μs


tensor(14)

#### One of the most common errors in deep learning (shape errors)
* Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and  sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.


In [29]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

* torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
* tensor.T - where tensor is the desired tensor to transpose.

In [30]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [31]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [32]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [33]:
# You can also use torch.mm() which is a short for torch.matmul().

# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])